export const packetNames = {
    game: {
        GlobalFailCode: 'game.GlobalFailCode',

        PlayerInfo: 'game.PlayerInfo',
        TransformInfo: 'game.TransformInfo',
        StatInfo: 'game.StatInfo',

        InventoryInfo: 'game.InventoryInfo',
        ItemInfo: 'game.ItemInfo',
        EquipmentInfo: 'game.EquipmentInfo',

        ScreenText: 'game.ScreenText',
        ScreenTextAlignment: 'game.ScreenTextAlignment',
        Color: 'game.Color',

        DungeonInfo: 'game.DungeonInfo',
        MonsterStatus: 'game.MonsterStatus',
        ActionSet: 'game.ActionSet',
        PlayerStatus: 'game.PlayerStatus',
        BattleLog: 'game.BattleLog',
        BtnInfo: 'game.BtnInfo',

        C_SigninRequest: 'game.C_SigninRequest',
        S_SigninResponse: 'game.S_SigninResponse',
        C_LoginRequest: 'game.C_LoginRequest',
        S_LoginRequest: 'game.S_LoginRequest',
        C_EnterRequest: 'game.C_EnterRequest',
        S_EnterResponse: 'game.S_EnterResponse',
        S_SpawnNotification: 'game.S_SpawnNotification',
        S_DespawnNotification: 'game.S_DespawnNotification',
        C_MoveRequest: 'game.C_MoveRequest',
        S_MoveResponse: 'game.S_MoveResponse',
        C_AnimationRequest: 'game.C_AnimationRequest',
        S_AnimationResponse: 'game.S_AnimationResponse',
        C_ChatRequest: 'game.C_ChatRequest',
        S_ChatResponse: 'game.S_ChatResponse',
        C_EnterDungeonRequest: 'game.C_EnterDungeonRequest',
        S_EnterDungeonResponse: 'game.S_EnterDungeonResponse',
        C_EquipItemRequest: 'game.C_EquipItemRequest',
        S_EquipItemResponse: 'game.S_EquipItemResponse',
        C_UnequipItemRequest: 'game.C_UnequipItemRequest',
        S_UnequipItemResponse: 'game.S_UnequipItemResponse',
        C_BuyItemRequest: 'game.C_BuyItemRequest',
        S_BuyItemResponse: 'game.S_BuyItemResponse',
        C_SellItemRequest: 'game.C_SellItemRequest',
        S_SellItemResponse: 'game.S_SellItemResponse',
        S_BattleLogNoification: 'game.S_BattleLogNoification',
        S_SetPlayerHpNotification: 'game.S_SetPlayerHpNotification',
        S_SetPlayerMpNotification: 'game.S_SetPlayerMpNotification',
        S_SetMonsterHpNotification: 'game.S_SetMonsterHpNotification',
        C_PlayerActionRequest: 'game.C_PlayerActionRequest',
        S_PlayerActionResponse: 'game.S_PlayerActionResponse',
        S_MonsterActionNotification: 'game.S_MonsterActionNotification',
        S_LeaveDungeonResponse: 'game.S_LeaveDungeonResponse',

    },
};